Makefile, README.md
*Description of changes:*
This adds some details on how to render the site locally. It also adds a
Makefile target that will use a containerized `hugo` to make it easier
for general developers to be able to view changes locally.
By submitting this pull request, I confirm that my contribution is made under the terms of the licenses outlined in the LICENSE-SUMMARY file.
=> Add local rendering instructions

DIRECTORY-STRUCTURE.md
Closes #39
Switches DIRECTORY-STRUCTURE.md to use directories instead of individual files, and describe why that is the case.
=> switch DIRECTORY-STRUCTURE.md to directories

content/en/os/1.13.x/concepts/_index.markdown, content/en/os/1.13.x/concepts/updating-bottlerocket/index.markdown, content/en/os/1.13.x/update/_index.markdown, content/en/os/1.13.x/update/guidelines/index.markdown
Closes # n/a
Adds `description` front matter to the existing content directories (`_index.markdown`) and content markdown.  
=> adds descriptions to category and content pages

content/en/faqitems/access-1-regaining-access.markdown, data/README.md, data/versions/current.toml, layouts/shortcodes/ver-ref.html
Closes # n/a
This adds the `ver-ref` shortcode that is aware of the site's structure (language, project, versions). So, if you want to create a link to the latest version of a specific file in the docs, you can specify it as so:
```
{{< ver-ref project="os" page="/path/to/page" >}} link text{{< /ver-ref >}}
```
The current version is specified in the `/versions/current` data file on a per project basis.
So, if the current version is set to 1.20.1, the above link will point to `/en/os/1.20.x/path/to/page`. When the next version is released and the `/versions/current` file is changed to 1.21.0, the link will then point to `/en/os/1.21.x/path/to/page`.
By submitting this pull request, I confirm that my contribution is …
=> Adds shortcode for un-versioned links

DIRECTORY-STRUCTURE.md
Related to #14 
Suggests a location for where a new "packages" page should reside.
The "packages" page would contain an inventory (table/list) of all the included software versions for each release.
=> directory structure: suggest new packages page

content/en/os/1.13.x/packages/_index.markdown, layouts/shortcodes/packages-table.html, scripts/software-versions-inventory/README.md, scripts/software-versions-inventory/software-versions-inventory.sh
Closes #14 
Adds a modified version of [Kyle's script](https://github.com/bottlerocket-os/project-website/issues/14#issuecomment-1270245319) that extracts software versions from a Bottlerocket OS repository and outputs them to a Hugo page. Documentation for that script is included.
Also adds the required Hugo shortcode layout to render a table of the software versions.
Software version table pages will live as `index.markdown` files inside a subdirectory under the new `content/en/os/MINOR_RELEASE/packages/` directory. The subdirectory name would be the patch release version e.g. `1.13.0`, `1.13.1`, etc.
the terms of the licenses outlined in …
=> packages: add script and shortcode

content/en/os/1.13.x/install/quickstart/aws/host-containers/index.markdown
Closes #72
Adds `/etc/os-release` content for the ECS variant/tab on the "Host Containers" page in the quickstarts section
=> host containers: add ECS output

content/en/os/1.13.x/concepts/variants/index.markdown
Closes #68 
Changes `arm64` to `aarch64` to accurately show the Bottlerocket variant naming convention.
=> variants: "arm64" to "aarch64"

content/en/os/1.13.x/concepts/variants/index.markdown
Closes #67
Adds `-x86_64-` to the variant names in the "Variants, updating, & migrating" table on the Variants page.
=> variants: fix arch in the updating table

assets/scss/_styles_project.scss, content/en/os/_index.markdown, layouts/shortcodes/subsections-list.html
Closes #65
- Adds an explanation to the section page for OS
- Adds a shortcode called "subsections-list" that allows for relocating the listing the sections page to anywhere in the context
- Adds supporting styles for the shortcode
=> Adds explaination of OS section, subsection-list shortcode

content/en/os/1.13.x/concepts/shell-less-host/index.markdown
Closes #84
- Removes incorrect reference to on-prem variants having an default enabled admin container.
=> Remove reference to on-prem admin containers

assets/scss/_styles_project.scss
Closes #121
Unsets CSS that causes code blocks to 80% of screen width below "medium" size screens (e.g. mobile)
=> Code blocks on small screens are not weirdly narrow

content/en/faqitems/settings-1-what-language-is-used.markdown
Closes #102 
Adds a FAQ item that explains that TOML is used for defining settings, as well as linking to TOML examples.
=> FAQ: add language used for settings

content/en/faqitems/on-prem-1-manage-onprem-node-like-cloud-node.markdown
Closes #101 
Adds a FAQ item explaining that either the control container or host containers can be used to manage an on-prem Bottlerocket node.
=> FAQ: add managing onprem nodes like cloud nodes

.github/PULL_REQUEST_TEMPLATE, .github/workflows/generate-package-list.yml
Closes #146 
Adds a Github Action to this repo which:
- Clones this repo
- Clones the Bottlerocket OS repo at a specified tag (patch release)
- Generates the package version list for that patch release
- Makes a new branch on this repo for that new package version list page
- Opens a PR against this repo for the new package version list page
=> github actions: add package list generation

.github/workflows/variant-kernel-info.yaml
Closes #148 
Adds a Github Action to this repo which:
- Clones this repo
- Clones the Bottlerocket OS repo at a specified tag (patch release)
- Generates the variant kernel info files for the given minor release, from a specific patch release tag
- Makes a new branch on this repo for that new variant kernel info
- Opens a PR against this repo for the new variant kernel info
=> github actions: add variant kernel info generation

content/en/_index.markdown, layouts/shortcodes/nav-bar-open.html
Closes # n/a
**Description of changes:** 
When landing on `/en/` (Documentation) the OS section is closed. This is a little confusing, so this PR adds a shortcode that will auto open the navbar when included on specific pages. Additionally, this PR includes a modification to the index of `/en/` that triggers the auto-open of on the source page for `/en/`
=> adds menu auto-open for `/en/`

.github/workflows/hugo.yaml
Closes # n/a
Changes order of action steps as previous order caused the nested directory to trigger the final step to clear out the parent ("Deleting the contents of ... ")
=> switching action order to avoid delete of previous action

config.toml
Closes #178
Fixes an issue where the social preview was incorrectly defaulting to Hugo's description.
=> fixes og:description defaulting to hugo

assets/scss/_styles_project.scss, content/en/os/latest.markdown, data/versioned.toml, layouts/partials/hooks/head-end.html, layouts/partials/version-banner.html, layouts/shortcodes/latest-redirect.html
Closes #191 
This PR accomplishes three related things:
1. Provides a notice to users when they are browsing old documentation.
2. Provides logic to create evergreen links
3. Adds a `rel=canonical` html tag to previous version pages to prevent google from indexing old versions and never pointing to the newer versions.
---
This is a little bit complicated to implement with a static site but here is the flow:
1. The template hook `layouts/partials/hooks/head-end.html` does the primary logic to determine if the page is out-of-date. It does this by re-parsing the source file names and looking for a newer version based on the Site Data. It also adds the `rel=canonical` if required.
2. I overrode the the partial …
=> adds notice for old docs and redirection logic

content/en/os/1.14.x/concepts/api-driven/index.markdown
Closes #194
This changes adds a few missing pieces to the API documentation. 
These additions are needed to move the primary documentation for the API from the readme of bottlerocket-os/bottlerocket to [*/concepts/api-driven/](https://bottlerocket.dev/en/os/1.14.x/concepts/api-driven/) and not lose any missing info.
=> levels the API driven docs with content in readme

scripts/software-versions-inventory/software-versions-inventory.sh
N/A
The software-versions-inventory.sh script gets a nicely formatted list of packages for each Bottlerocket version and renders it into a easily readable markdown table with a lot of good details. This table currently ends up listing the packages in whatever order the `find` command returns the package names from intrspecting the repo contents, which means it is a somewhat randomized list of packages that requires searching through if you are looking for a specific item.
This is a minor change to sort the results of the `find` command so that this table is always in alphabetical order, making it a little easier to find what you're looking for.
By submitting this pull request, I confirm that my contribution is made …
=> Sort package inventory for versions script

data/homepagediagrams/variants.toml, includes/homepage/minimal.markdown, layouts/shortcodes/diagram_variants.svg
Closes #200
This makes the homepage animated digram reasonably updatable. 
- Move the SVG into a shortcode from an include file
- Make the SVG interpolate values from the data file `data/homepagediagrams/variants.toml`
=> SVG driven by data file

content/en/os/_index.markdown, content/en/os/latest.markdown, layouts/partials/version-banner.html, layouts/shortcodes/subsections-list.html
Closes #212
Adds an exception to page parameters that blocks version warnings on pages as needed.
=> fix unintended version warning

METADOC-SETTING-DOCS-DSL.md, layouts/partials/settings-setting-individual.html, layouts/partials/settings_inner_page_link.html, layouts/shortcodes/settings.html
Closes # n/a
- Adds `deprecated` metadoc
- Adds template changes to display a "Deprecated" label on any setting with `deprecated` = `true`
=> Adds `deprecation` to model for settings documentation DSL

content/en/os/1.15.x/concepts/variants/index.markdown, content/en/os/1.15.x/install/quickstart/aws/ecs/index.markdown, content/en/os/1.15.x/install/quickstart/aws/host-containers/index.markdown, data/versions/current.toml, layouts/shortcodes/diagram_variants.svg, layouts/shortcodes/os-release-example.html
Closes #198
Adapts multiple pieces of content to use ECS-2 variant
- Modifies variant conceptual docs to use ecs-2 (`en/os/1.15.x/concepts/variants`)
- Updates the ssm parameter for ECS-2 on the quickstart (`en/os/1.15.x/install/quickstart/aws/ecs`)
- Adds k8s and ecs version info into current version data file
- Refactors the os-release example on the host containers documentation into a shortcode that will autoupdate
- Changes ECS version on SVG
=> adapts content for ecs-2 and 1.15

content/en/os/1.15.x/api/settings/bootstrap-containers/_index.markdown, content/en/os/1.15.x/concepts/bootstrap-containers/_index.markdown, data/settings/1.15.x/bootstrap-containers.toml
Closes #238 
This completes the documentation for bootstrap container in 1.15.x.
Note: none of this is _new_ content but just adding the existing (and unchanged) content from 1.14.x docs (recently merged) to 1.15.x
=> moves 1.14.x boostrap contaienrs into 1.15.x

content/en/os/1.15.x/api/settings/kernel/_index.markdown, data/settings/1.15.x/kernel.toml
#234 
- Duplicates 1.14.x kernel settings reference to apply to 1.15.x. No new docs in this PR.
=> Housekeeping: duplicates 1.14.x kernel settings ref to 1.15.x

content/en/os/1.15.x/api/settings/boot/_index.markdown, data/settings/1.15.x/boot.toml
Closes #235 
Adds setting reference for boot related settings
=> adds setting reference for `settings.boot.*`

content/en/os/1.15.x/api/settings-index/_index.markdown, content/en/os/1.15.x/api/settings-list/_index.markdown, data/settings/1.15.x/oci-defaults.toml, layouts/shortcodes/all-settings.html
Closes # n/a
Adds a page that provides a simple list of every bottlerocket setting for a given version.
Currently this page is not linked but generated (`/en/os/1.15.x/api/settings-index/`). At this point, it should be considered a debugging tool, as it can give the impression that it's all setting not just all _documented_ settings.
At a later point, once all settings are merged, it can be exposed as a link.
Additionally this PR contains a small fix to `oci-defaults` that fixes a markup error that obscured one setting.
=> All Settings Index

data/settings/1.15.x/ecs.toml, data/settings/1.15.x/kernel.toml, data/settings/1.15.x/kubernetes.toml
Closes #318
- `settings.ecs.image-cleanup-wait` added (also fixes mixed up description with `task-cleanup-wait`)
- `settings.kernel.modules.<name>.autoload` added
- `settings.kubernetes.standalone-mode` added
- `settings.kubernetes.static-pods.<custom identifier>.enabled` fixes bad rendering
- `settings.kubernetes.static-pods.<custom identifier>.manifest` fixes bad rendering
=> Audit fixes

assets/scss/_styles_project.scss, content/en/os/1.15.x/concepts/bootstrap-containers/_index.markdown, content/en/os/1.15.x/concepts/host-containers/_index.markdown, layouts/shortcodes/components_diagram.html, layouts/shortcodes/setting-reference.html
Closes #254
- Adds concept documentation for host containers
- Adds a short code to reference settings by name instead of by (relative) URL
- Changes reference on bootstrap containers concept documentation to point to this instead of the quickstart
=> Concept docs: Host containers 

content/en/os/1.14.x/api/settings/_index.markdown, content/en/os/1.15.x/api/settings/_index.markdown
Closes #308 
Removes messages about 1.15.x settings reference being incomplete. 
Updates message about 1.14.x being incomplete and points to the 1.14.3 tagged readme.
=> removes incomplete notice, adds reference for 1.14.x

assets/scss/_styles_project.scss, content/en/os/1.15.x/version-information/packages-by-variant/index.markdown, layouts/shortcodes/packages-by-variant.html
Closes #36
- adds a shortcode that has a chart that lists all variants and which packages they have
- Adds a page that hosts this shortcode
- Adds styles
One note: this is a responsive chart but it may exceed the width of narrow monitors so it does cause a contained horizontal table scroll. 
The page ends up producing a chart like this:
=> Adds page that outlines packages in each variant

data/settings/1.15.x/kernel.toml
**Issue number:** n/a
```
This reverts commit b9924cba128b08b254d2f689848ed13c22149cd0.
The `kernel.modules.<name>.autoload` feature is not part of the 1.15.x branch. It will be released as part of 1.16.0 instead.
```
The missing feature in 1.15.0 was pointed out on the linked discussion https://github.com/bottlerocket-os/bottlerocket/discussions/3050 I closed prematurely, claiming it was part of 1.15.
=> Revert "fixes missed kerenl autoload"

data/settings/1.15.x/kubernetes.toml
Closes # n/a
Further review of version to version README and setting reference revealed skipped setting `seccomp-default`
=> Adding missed setting from after inital review

data/settings/1.15.x/kernel.toml, data/settings/1.15.x/kubernetes.toml
n/a - see #335
Moves  missing `settings.kubernetes.seccomp-default` to prod.
=> Move to Prod: `settings.kubernetes.seccomp-default`

data/settings/1.16.x/kernel.toml
Closes #332 
Re-adds kernel auto load setting reference only for Bottlerocket 1.16.x settings reference
=> Re-add 1.16.x kernel autoload setting reference

data/settings/1.14.x/ecs.toml, data/settings/1.15.x/ecs.toml, data/settings/1.16.x/ecs.toml
Closes #357
Flips the default value for `settings.ecs.image-cleanup-enabled` to the correct value across all documented versions.
=> flip default value for `image-cleanup-enabled`

data/homepagediagrams/variants.toml, data/settings/1.14.x/ecs.toml, data/settings/1.15.x/ecs.toml, data/settings/1.16.x/ecs.toml
Closes # n/a
Moves to prod: correction for default value of setting
=> Move to Prod: Correct default value for `setting.ecs.image-cleanup-enabled`

content/en/os/1.15.x/api/settings-index/_index.markdown, content/en/os/1.16.x/api/settings-index/_index.markdown, layouts/partials/setting-list-item.html, layouts/shortcodes/all-settings.html
Closes #362 
- Unhides the setting index for 1.15.x and 1.16.x (e.g. `/en/os/1.16.x/api/settings-index/`
- On 1.16.x (and forward, unless turned off) it will render a `New for 1.16.x` badge on newly added settings in the index
=> adds "new for x.x.x" badge and unhides settings index

content/en/os/1.15.x/api/settings-index/_index.markdown, content/en/os/1.16.x/api/settings-index/_index.markdown, data/versions/current.toml, layouts/partials/setting-list-item.html, layouts/shortcodes/all-settings.html
Closes # n/a
Moves the full index of settings to prod along side a "new for x.x.x" badge
=> Move to Prod: Setting reference index and new for x.x.x

data/settings/1.14.x/motd.toml, data/settings/1.15.x/motd.toml, data/settings/1.16.x/motd.toml
Closes # n/a
The text in the example indicates that the motd will show up in the control container. That's not the case.
=> Fixes misleading MOTD example.

content/en/os/1.16.x/update/methods/in-place/index.markdown
"workloads are not be drained from the node" could be interpreted as "workloads are not (to) be drained from the node" instead of "workloads will not be drained from the node".
=> Improvement to docs for place updates using SSM and workload draining

assets/scss/_styles_project.scss, content/en/os/1.16.x/install/_index.markdown, content/en/os/1.16.x/install/quickstart/aws/ecs/index.markdown, content/en/os/1.16.x/install/quickstart/aws/host-containers/index.markdown, content/en/os/1.16.x/install/quickstart/aws/k8s/index.markdown, layouts/shortcodes/breadcrumb-remove.html, layouts/shortcodes/hide-and-re-highlight-menu.html, layouts/shortcodes/redirect-list.html
Closes #85
This fixes #85 by adding 3 shortcodes:
- `{{ redirect-list }}` that allows injection of another section's list
- `{{ hide-and-re-highlight-menu }}` that hides portion of the nav menu based on parameters
- `{{ breadcrumb-remove }}` that hides portions of the bread crumbs based on parameters
Additionally, it adds these shortcodes to the pages under `Install`.
This results in a menu that skips over the single-entry `Quickstarts` and `AWS` sections and retains the same URLs.
=> adds functionlity that hides single-entry lists in the menu

content/en/os/1.17.x/install/_index.markdown, content/en/os/1.17.x/install/quickstart/aws/ecs/index.markdown, content/en/os/1.17.x/install/quickstart/aws/host-containers/index.markdown, content/en/os/1.17.x/install/quickstart/aws/k8s/index.markdown
Closes #85
This adds the snippets to handle a collapsable menu on 1.17.x docs branch. No new code or content here, just pulling forward changes made from 1.16.x to 1.17.x
=> port in the quickstart menu collapse snippets from 1.16.x

.github/workflows/nvidia-driver-versions.yml
Closes #373
Adds workflow to allow for collection of Nvidia driver versions via github actions
=> adds nvidia driver workflow for actions

assets/scss/_styles_project.scss
Closes #348
Adds new CSS to fix bolding.
**Note**: This is really patching over an issue with the upstream template. For some reason some "pages" are being rendered as "sections" (e.g. pages with children) by sidebar template in Docsy. Our docsy version is based on Bootstrap 4 and the current release of Docsy uses Boostrap 5 but it's unclear if updating the template would _solve_ the issue here as the code that generates the sidebar between our version and the most recent seems to be the same. I suspect it's some lurking corner case interaction between our customizations and a subtle bug upstream. Regardless, this patch seems to solve it the issue but it may become irrelevant (or worse) if we ever update.
By …
=> Fixes issue with bolding on sidebar menu

content/en/_index.markdown, data/project_long_names.toml, data/repos/os.toml, layouts/shortcodes/current-full-version.html
Closes #369
- adds shortcode for displaying current version and link to github release
- Adds metadata file that connects website 'project' section short forms to longer forms
- Adds current version shortcode to `/en/`
=> Add a current version box to documentation homepage.

content/en/os/1.15.x/concepts/host-containers/_index.markdown, content/en/os/1.16.x/concepts/host-containers/_index.markdown, content/en/os/1.17.x/concepts/host-containers/_index.markdown, content/en/os/1.18.x/concepts/host-containers/_index.markdown, content/en/os/1.19.x/concepts/host-containers/_index.markdown
Closes #425
Fixes typo when SSM is referred to "SMM" across several docs versions.
=> fix SSM typo in concepts on 1.15.x to 1.19.x

content/en/_index.markdown, content/en/brupop/latest.markdown
Closes # n/a
Moves to prod an application the existing evergreen link forwarder used in `/en/os` for use in `/en/brupop`
=> Move to Prod: Forwarder for Brupop

data/settings/1.16.x/kernel.toml, data/settings/1.17.x/kernel.toml, data/settings/1.18.x/kernel.toml, data/settings/1.19.x/kernel.toml
**Issue number:** https://github.com/bottlerocket-os/bottlerocket/issues/3747
```
kernel.modules: Reference boot.kernel-parameters for module options
Users of Bottlerocket had asked for an easy way to set module parameters
through user data [0]. That way already exists through kernel-parameters.
Document that settings.boot.kernel-parameters is to be used to set
module options.
Details on why adding extra settings under settings.kernel.modules to
achieve this can be found on the issue [1]
[0] https://github.com/bottlerocket-os/bottlerocket/issues/3747
[1] https://github.com/bottlerocket-os/bottlerocket/issues/3747#issuecomment-1954792175
Signed-off-by: Leonard Foerster <foersleo@amazon.com>
```
I am not quite sure if just linking from the module settings to …
=> Document where to set kmod parameters from the `settings.kernel.modules` documentation

config.toml, layouts/_default/baseof.html, layouts/partials/footer.html, layouts/partials/hooks/head-end.html, layouts/partials/navbar.html, layouts/shortcodes/all-settings.html
Closes # n/a
I had person tell me (off github) that the site wasn't building with the latest hugo.
Upon investigation, I discovered two issues:
1) Symlink support was removed between `0.104.2` and current release (`0.123.8`)
2) The templates used `.Page.File.Dir` and this was causing an obscure error with hugo with the newer versions (see https://github.com/gohugoio/hugo/issues/12221)
This PR works around both issues by moving the symlinks to `module.mounts` and parsing `.Page` to get the path as a string (less than ideal, but I want to unblock usage with the most recent hugo).
=> removes symlinks, refactors .Page.Dir references for new Hugo version

.github/workflows/hugo.yaml, Makefile, assets/scss/_styles_project.scss
Closes # n/a Related to #449 
Small tweaks to adapt site to new/current version of Hugo
- Change to new docker container for `make preview`
- Adds alternate make for Finch instead of Docker in `make preview`
- Fix two rendering difference between hugo version
- Change the github workflow to use the new version
=> adapt to new hugo version

data/settings/1.19.x/ecs.toml
Closes #442
Add missing documentation for `settings.ecs.enable-container-metadata`
=> ecs: add `settings.ecs.enable-container-metadata` for 1.19.x

layouts/partials/settings-example-tab-pane.html, layouts/partials/settings-setting-individual.html
Closes #447 
Evaluates example values to see if they have compound toml that requires heredoc on the command line. This only affects rendering of settings which have a value that is encoded as a toml in a string.
So, the following settings:
`settings.kubernetes.allowed-unsafe-sysctls`
`settings.kubernetes.cluster-dns-ip`
`settings.kubernetes.cpu-manager-policy-options`
`settings.dns.name-servers`
`settings.dns.search-list`
`settings.network.no-proxy`
`settings.ntp.time-servers`
Before:
After:
=> fixes issues with compound toml apiclient examples

content/en/os/1.23.x/api/settings/kubelet-device-plugin/_index.markdown, content/en/os/1.24.x/api/settings/kubelet-device-plugin/_index.markdown, content/en/os/1.25.x/api/settings/kubelet-device-plugin/_index.markdown, data/settings/1.23.x/kubelet-device-plugin.toml, data/settings/1.24.x/kubelet-device-plugin.toml, data/settings/1.25.x/kubelet-device-plugin.toml
* Adds new settings for `kubelet-device-plugin.*` to 1.23/1.24/1.25
* Adds time-slicing content to `kubelet-device-plugin.*` 1.25
=> Adding kubelet-device-plugin for 1.23/1.24 and time-slicing for 1.25

METADOC-SETTING-DOCS-DSL.md, data/settings/1.30.x/kubernetes.toml, layouts/partials/settings-example-tab-button.html, layouts/partials/settings-example-tab-pane.html, layouts/partials/settings-setting-individual.html
- Add new documentation
- Extend settings reference example highlighting to support `yaml`. We don't support yaml as user data so this new `tabpanel` highlight is only active when examples are explicitly marked with `direct_yaml`. It is disabled in all other cases to not confuse between specfile examples and userdata examples.
=> Add documentation for device-ownership settings

data/settings/1.14.x/oci-defaults.toml, data/settings/1.15.x/oci-defaults.toml, data/settings/1.16.x/oci-defaults.toml, data/settings/1.17.x/oci-defaults.toml, data/settings/1.18.x/oci-defaults.toml, data/settings/1.19.x/oci-defaults.toml, data/settings/1.20.x/oci-defaults.toml, data/settings/1.21.x/oci-defaults.toml, data/settings/1.22.x/oci-defaults.toml, data/settings/1.23.x/oci-defaults.toml, data/settings/1.24.x/oci-defaults.toml, data/settings/1.25.x/oci-defaults.toml, data/settings/1.26.x/oci-defaults.toml, data/settings/1.27.x/oci-defaults.toml, data/settings/1.28.x/oci-defaults.toml, data/settings/1.29.x/oci-defaults.toml, data/settings/1.30.x/oci-defaults.toml, data/settings/1.31.x/oci-defaults.toml, data/settings/1.32.x/oci-defaults.toml, data/settings/1.33.x/oci-defaults.toml, data/settings/1.34.x/oci-defaults.toml, data/settings/1.35.x/oci-defaults.toml, data/settings/1.36.x/oci-defaults.toml, data/settings/1.37.x/oci-defaults.toml, data/settings/1.38.x/oci-defaults.toml, data/settings/1.39.x/oci-defaults.toml, data/settings/1.40.x/oci-defaults.toml, data/settings/1.41.x/oci-defaults.toml
Closes https://github.com/bottlerocket-os/bottlerocket/issues/4583
Current `oci-defaults.resource-limits.max-open-files` defaults only applies to `k8s` variants. Updating to include defaults for `ecs` variants.
Applies to versions 1.14.x to 1.41.x
=> fix: oci-defaults.resource-limits.max-open-files defaults for 1.14.x+

data/settings/1.40.x/kubelet-device-plugins.toml, data/settings/1.41.x/kubelet-device-plugins.toml, data/settings/1.42.x/kubelet-device-plugins.toml
Closes #533
This adds the documentation for enabling CDI through the Kubernetes device plugin in Bottlerocket 1.40.x through 1.42.x. As part of this change, I fixed a problem with the documentation where the "nvidia" tag was referenced but it didn't exist anywhere, resulting in an empty bullet point added to the "See" section of the `device-list-strategy` documentation. Adding `nvidia-cdi` fixed the problem, as the tag does exist.
=> Add CDI documentation
