.github/PULL_REQUEST_TEMPLATE

This cleans up the PR template formatting to more closely match what we
use in other Bottlerocket repos.
By submitting this pull request, I confirm that my contribution is made under the terms of the licenses outlined in the LICENSE-SUMMARY file.

Update PR template to match main repo

---

STYLE-GUIDE.md

Closes #22 
**Description of changes:** Adds a style and writing guide.

adds style guide

---

DIRECTORY-STRUCTURE.md

Closes #13
**Description of changes:** provides detailed structure to the URL and content locations

adds directory stucture document

---

DIRECTORY-STRUCTURE.md

Part of #16 
Add the FAQ to the directory structure plan - localizable but not versioned.

DIRECTORY-STRUCTURE.md: add FAQ

---

content/en/1.13.0/concepts/updating-bottlerocket.markdown
content/en/1.13.x/concepts/updating-bottlerocket.markdown

Closes #18 
This PR adds a document that outlines a few ways to update Bottlerocket.

add doc: upgrading Bottlerocket

---

DIRECTORY-STRUCTURE.md
content/en/os/1.13.x/update/guidelines.markdown

Closes #21
Adds the directory structure and initial doc for Updating Guidelines.

updating guidelines: add directory structure and initial doc

---

DIRECTORY-STRUCTURE.md

Regarding #17 
Adds the "regaining access" document to the directory structure

directory structure: add "regaining access"

---

DIRECTORY-STRUCTURE.md

**Issue number:** N/a, related to #34
Updates the structure to document to reflect the required changes to the `all` and `faq` directories 

modified to reflect headless bundle for FAQ

---

content/en/os/1.13.x/concepts/variants/index.markdown

Closes # n/a
Add a document that explains Bottlerocket variants in the 'concepts' section of documentation.

adds a conceptual document for variants

---

content/all/_index.md
content/en/os/1.13.x/concepts/restricted-filesystem/index.markdown
includes/os/1.13.x/dm-verity-with-change.markdown
includes/os/1.13.x/dm-verity-without-change.markdown

Closes # n/a
Documents concepts behind SELinux, dm-verity and tmpfs

adds concept documentation about file system restrictions

---

content/en/os/1.13.x/concepts/shell-less-host/index.markdown

Closes # n/a
Adds documentation for Bottlerocket's lack of a shell (effectively superseding much exposition in [the README's "Exploration" section](https://github.com/bottlerocket-os/bottlerocket#exploration).

adds concept docs for shell-less host

---

assets/scss/_home_svg.scss
content/en/os/1.13.x/concepts/api-driven/index.markdown

Closes # n/a
Add conceptual documentation on bottlerocket's API.

adds api driven documentation

---

content/en/os/1.13.x/install/_index.markdown
content/en/os/1.13.x/install/quickstart/_index.markdown
content/en/os/1.13.x/install/quickstart/aws/_index.markdown
content/en/os/1.13.x/install/quickstart/aws/host-containers/index.markdown
content/en/os/1.13.x/install/quickstart/aws/k8s/index.markdown

Closes #55 
Adds a quickstart tutorial for Bottlerocket on Amazon EKS

quickstart: add EKS quickstart

---

content/en/os/1.13.x/concepts/variants/index.markdown

Closes n/a
Fixes a small typo on the variants page

variants: fix typo

---

content/en/os/1.13.x/install/_index.markdown
content/en/os/1.13.x/install/quickstart/_index.markdown
content/en/os/1.13.x/install/quickstart/aws/_index.markdown
content/en/os/1.13.x/install/quickstart/aws/ecs/index.markdown
content/en/os/1.13.x/install/quickstart/aws/host-containers/index.markdown
content/en/os/1.13.x/install/quickstart/aws/k8s/index.markdown

Closes #56 
Adds a quickstart for ECS. Builds on top of the EKS quickstart PR (please merge that first).

quickstart: add ECS quickstart

---

assets/scss/_styles_project.scss
assets/scss/_variables_project.scss

Closes # n/a
Changes headline font to _IBM Plex Sans Condensed_ and body to _IBM Plex Sans_

Adds custom font

---

content/en/faqitems/general-1-test-question.markdown
content/en/faqitems/releases-1-another-test.markdown
layouts/shortcodes/faqlist.html

Closes #69 
- Adds hash linking to each faq item
- removes dummy content
- adds deterministic ordering

adds ordering, hash linking, removes dummy content

---

content/en/faqitems/troubleshooting-1-bootstrap-container-logs.markdown

Closes #45 
Adds a FAQ item informing users that bootstrap container logs are accessible from the system journal.

FAQ item: bootstrap logs

---

data/versions/current.toml

Closes #n/a
Changes data file to reflect 1.13.1 patch release.

bumps current version data to 1.13.1

---

content/en/os/1.13.x/concepts/updating-bottlerocket/index.markdown

Closes #73 
Removes "Bottlerocket" from the page title so that it semantically fits with the other titles in the Concepts section.

updating: remove "bottlerocket" from title

---

content/en/_index.markdown

Closes #64
Adds a landing page on the language root which describes the site.

adds documentation landing page

---

config.toml

Closes #91
Removes relative link in navbar that caused weird navigation in subpages

removes relative link from brand link in navbar

---

config.toml
content/en/faqitems/access-1-regaining-access.markdown
content/en/faqitems/troubleshooting-1-bootstrap-container-logs.markdown
includes/homepage/intro.markdown
layouts/shortcodes/center-button.html
layouts/shortcodes/ver-ref.html
third-party/google/docsy/layouts/partials/navbar.html

Closes # n/a
Fixes issues revealed to any links/urls which did a explicit relative reference to `/foobar.
This allows the site to be deployed at a subdirectory.

Remove relative/root links

---

content/en/os/1.13.x/update/locking-to-a-specific-release/index.markdown

Closes #96 
Fixes links on the Version Locking page - a content item was moved

fix links on version locking page

---

assets/scss/_styles_project.scss
content/en/os/1.13.x/api/_index.markdown
content/en/os/1.13.x/api/endpoints/index.markdown
content/en/os/1.13.x/concepts/_index.markdown
content/en/os/1.13.x/install/_index.markdown
content/en/os/1.13.x/login/_index.markdown
content/en/os/1.13.x/update/_index.markdown
content/en/os/1.13.x/version-information/_index.markdown
static/external/openapi.yaml

Closes # n/a
Imports OpenAPI from bottlerocket-os/bottlerocket, adds styling, fixes order of left hand nav to make API push to bottom

imports openapi spec and orders left hand nav

---

.github/ISSUE_TEMPLATE/content.md
.github/ISSUE_TEMPLATE/rendered.md

Closes # n/a
Adds github issue templates

adds issue templates

---

.github/ISSUE_TEMPLATE/content.md

Closes # n/a
Adds github issue templates

fixes markdown issue in template

---

.github/ISSUE_TEMPLATE/rendered.md

Closes # n/a
Adds github issue templates

Final fix to issue template

---

content/en/os/1.13.x/concepts/api-driven/index.markdown
content/en/os/1.13.x/concepts/components/index.markdown
includes/homepage/safe-update.markdown

Fix a few grammar nits. Deleted some extraneous words.
N/A
A few small nits. Removed a few words.

grammar and style nits

---

content/en/faqitems/access-1-how-do-i-ssh-into-bottlerocket.markdown
content/en/faqitems/fleet-management-1-how-do-i-ssh-into-bottlerocket.markdown

Closes #98
Adds a FAQ about using SSH to access Bottlerocket. Recommends SSM via the control container but also points to SSH steps in case SSM is for some reason out of the question.

FAQ: add SSH question

---

content/en/faqitems/eks-1-how-to-do-fault-injection.markdown
content/en/faqitems/kubernetes-1-how-to-do-fault-injection.markdown

Closes #100 
Adds a FAQ noting that fault injection is possible with Bottlerocket on EKS.

FAQ: add fault injection on EKS

---

content/en/os/1.13.x/concepts/components/index.markdown

Closes #127 
Rephrases the explanation of host containers on the "Components" page in the "Concepts" section.

components: reword host containers explanation

---

content/en/faqitems/security-1-immutability-files-change-on-host.markdown

Closes #103 
Adds a FAQ item that explains the range of mutability on a Bottlerocket filesystem.

FAQ: add immutability of host files question

---

assets/scss/_styles_project.scss

Closes #120
Adds a smaller indent on more narrow screens (helps #115, maybe doesn't fully fix) and restores the indent on mobile (#120)

Adds indents on mobile/small menus

---

content/en/faqitems/fleet-management-2-scanning-cluster-software-vulns.markdown
content/en/faqitems/security-2-scanning-cluster-software-vulns.markdown

Closes #99 
Explains how to perform software vulnerability scanning for Bottlerocket (using Amazon Inspector)

FAQ: add software vulnerability scanning question

---

content/en/os/1.13.x/version-information/packages/1.13.2/index.markdown

Closes #139 
adds package version info for v1.13.2

packages: add package versions for v1.13.2

---

content/en/os/1.13.x/version-information/packages/1.13.3/index.markdown

Closes #140 
adds package version info for v1.13.3

packages: add package versions for v1.13.3

---

assets/scss/_home_svg.scss
includes/homepage/dm-verity-selinux.svg

Closes #117
- Adds media queries to remove columns on small width screens
- Adds fixes for home page rendering inconsistencies on small width screens 

adds homepage fixes for small diagrams

---

.github/ISSUE_TEMPLATE/content.md
.github/ISSUE_TEMPLATE/rendered.md

N/A
This is a trivial update to address a couple typos noticed in our issue templates.

Issue templates: Fix minor typos in template

---

assets/scss/_styles_project.scss

Closes #115
Adjust styles to give more horizontal width to left nav.

adds styles that fix left nav issues

---

assets/scss/_home_svg.scss
assets/scss/_styles_project.scss
assets/scss/_variables_project.scss

Closes #110
Changes colours and font sizes on the home page. See [this issue comment for details.](https://github.com/bottlerocket-os/bottlerocket-project-website/issues/110#issuecomment-1502223794).

fixes numerous accessibilty (ccr) issues

---

.github/workflows/hugo.yaml

Closes # N/a
- Adds file to tell GitHub to not build with Jekyll
- Adds workflow to build pages with Actions

Prepare Site to use Hugo for deployment on GitHub Pages

---

content/en/_index.markdown

Closes # n/a
Fixes small typo.

fixes spelling mistake on /en

---

content/en/_index.markdown
layouts/shortcodes/nav-bar-open.html

Closes # n/a
- Pushes changes to `/en/` to production

Pushes fixes to production

---

.github/workflows/hugo.yaml

Closes # n/a
Clones bottlerocket-os/bottlerocket during build stage to grab common source files for `/about/`: 'charter', 'code-of-conduct', 'securtity', 'trademark'

pull in 'about' directory file sources

---

.github/workflows/hugo.yaml

Closes # n/a
Corrects issue with GitHub Actions working differently than `act`

Bottlerocket-os/bottlerocket pull in, switch to actions/checkout

---

.github/workflows/hugo.yaml

Closes # n/a
**Description of changes:** Moves GH Action order change to production

Fixes GH Action order issue

---

assets/scss/_styles_project.scss
config.toml
content/all/about/security.markdown
layouts/partials/footer.html
third-party/google/docsy/layouts/partials/footer.html

Closes # n/a
Adds links to bottom nav for `/about/` section.

adds links to bottom nav and fixes content

---

.github/workflows/hugo.yaml
assets/scss/_styles_project.scss
config.toml
content/all/about/security.markdown
layouts/partials/footer.html
third-party/google/docsy/layouts/partials/footer.html

Closes # n/a
Push bottom nav changes to prod

Pushes bottom nav links to prod

---

includes/os/1.13.x/dm-verity-with-change.markdown

Closes #173
Fixes GOAT diagram to point to the correct circle in the rendered view
Note: It seems that the rendered view looks different than the text representation 🤦‍♂️, but the rendered view wins.

fixes diagram by pointing to the correct dot

---

includes/homepage/intro.markdown
includes/homepage/minimal.markdown
includes/homepage/safe-update.markdown

Closes #122 , #111, #114
Rewords multiple sentences to be more accurate.

Content fixes pre release

---

content/en/_index.markdown

Closes # na/
"disributions" -> "distributions"

fixes spelling error

---

config.toml
content/en/os/_index.markdown

N/A
Fix references to the main Bottlerocket repository

Fix references to the main Bottlerocket repository

---

config.toml
content/en/_index.markdown
content/en/os/_index.markdown

Closes # n/a
Moves #185 to production

Moves URL issue to production

---

data/versions/current.toml

Closes # n/a
increments data file to current patch. Patch variable is not currently rendered, so this is just housekeeping.

increments data file to 1.14.2

---

content/en/os/1.14.x/login/regaining-access/index.markdown

Closes #172
Adds step by step instructions. for 1.14.0 
It would be nice to include the specific IAM steps (which are tricky) but it adds significant complexity to the initial version

adds instructions for regaining access to ECS

---

data/versions/current.toml

Closes #208 
updates patch metadata for 1.14.3 release

fixes metadata for 1.14.3 release

---

content/en/os/1.15.x/api/reporting/index.markdown

Closes #220 
**Description of changes:** Adds documentation on the new report API usage.

Report API documentation

---

assets/scss/_styles_project.scss
content/en/os/1.14.x/api/settings/_index.markdown
content/en/os/1.14.x/api/settings/ecs/_index.markdown
content/en/os/1.14.x/api/settings/motd/_index.markdown
data/settings/1.14.x/ecs.toml
data/settings/1.14.x/motd.toml
layouts/partials/settings-example-tab-button.html
layouts/partials/settings-example-tab-pane.html
layouts/partials/settings-setting-individual.html
layouts/partials/settings-tag-individual.html
layouts/partials/settings_inner_page_link.html
layouts/shortcodes/settings.html

Contributes to #203
This adds templates and styles to render the DSL as described in #204. It also includes the `settings.ecs.*` and `settings.motd` ported from the bottlerocket-os/bottlerocket README.

Bottlerocket ECS settings documented in TOML DSL

---

layouts/shortcodes/settings.html

Closes #244 
- Adds conditional around 'Topic List' and 'Topics' on settings page, only shows these sections if they have tags.

fixes empty headings

---

content/en/os/1.14.x/api/settings/container-registry/_index.markdown
data/settings/1.14.x/container-registry.toml

Closes #228
- Converts Bottlerocket README container-registry settings docs into TOML.
- Clarifies language
- Normalizes examples 

adds container registry docs

---

layouts/partials/settings-setting-individual.html

Closes # n/a
Restores setting description rendering that was somehow eaten in the merge of #255

fixes missing setting description

---

content/en/os/1.14.x/api/settings/pki/_index.markdown
data/settings/1.14.x/pki.toml

Closes #236 
Adds settings reference for "Custom CA certificates" (aka `settings.pki.*`)

Add custom CA settings reference

---

data/homepagediagrams/variants.toml

Closes # n/a
Increments the versions in the homepage diagram to reflect 1.15.x release (ecs-2, k8s-1.28)

updates homepage diagrams for 1.15.0

---

assets/scss/_styles_project.scss
content/en/os/1.14.x/api/settings/bootstrap-containers/_index.markdown
content/en/os/1.14.x/concepts/bootstrap-containers/_index.markdown
data/settings/1.14.x/bootstrap-containers.toml
layouts/shortcodes/bootstrap_containers_diagram.html

Closes: #249 #238
- Adds settings reference for bootstrap containers
- Adds diagrams and styles for bootstrap containers
- Adds concept documentation for bootstrap containers

Bootstrap containers settings

---

content/en/os/1.14.x/concepts/bootstrap-containers/_index.markdown
content/en/os/1.15.x/concepts/bootstrap-containers/_index.markdown

**Issue number:** n/a
**Description of changes:** Fix a couple typos I noticed in the bootstrap containers pages.

fix typos in bootstrap containers pages

---

content/en/os/1.15.x/api/settings/cloudformation/_index.markdown
data/settings/1.15.x/cloudformation.toml

Closes #224
- Adds documentation on cloudformation signals

adds cloudformation settings docs

---

layouts/shortcodes/packages-table.html

Closes # n/a
Adds sorting to package versions on `/<lang>/os/<minor ver>/version-information/packages/<patch ver>/` in a template. See PR #280

Package sorting version list

---

content/en/os/1.14.x/api/settings/host-containers/_index.markdown
data/settings/1.14.x/host-containers.toml

Closes #237
Adds setting reference for `settiings.host-containers.*`
Note: the Bottlerocket README has additional information about host containers that belong somewhere else besides the settings reference. I will add an additional issue to track this. 

Adds host-container settings reference

---

content/en/os/1.15.x/api/settings/kubernetes/_index.markdown
data/settings/1.15.x/kubernetes.toml

1.15.x for #240 
Housekeeping only. Replicates k8s settings reference designed for 1.14.x into 1.15.x setting reference

housekeeping: replicates k8s-1.14.x settings ref into 1.15.x

---

content/en/os/1.15.x/api/settings/ntp/_index.markdown
data/settings/1.15.x/ntp.toml

Closes #233 
Adds docs for `settings.ntp.*`

adds docs for time servers/ntp

---

content/en/os/1.15.x/api/settings/autoscaling/_index.markdown
data/settings/1.15.x/autoscaling.toml

Closes #225 
- Adds reference for `settings.autoscaling.*`

Adds reference for autoscaling settings

---

content/en/os/1.15.x/api/settings/aws/_index.markdown
data/settings/1.15.x/aws.toml
data/settings/1.15.x/kubernetes.toml

Closes #239
Add setting reference for:
- `settings.aws.config`
- `settings.aws.profile`
- `settings.aws.credentials`
- `settings.aws.region`

adds `settings.aws.*` reference

---

content/en/os/1.15.x/api/settings/dns/_index.markdown
data/settings/1.15.x/dns.toml

Closes #292
- Adds settings reference for DNS

adds dns settings

---

assets/scss/_styles_project.scss
content/en/faqitems/security-3-disable-secureboot.markdown
content/en/os/1.15.x/concepts/chain-of-trust/index.markdown
includes/os/1.15.x/secure-boot.svg

Closes #217
Adds the following:
1. concepts page for chain of trust
2. SVG diagram for secure boot (+css styles)
3. faq question/answer for disabling secure boot.

Secure boot / chain of trust 1.15.x Docs

---

content/en/os/1.15.x/api/settings/container-runtime/_index.markdown
data/settings/1.15.x/container-runtime.toml

Closes #229
- Adds setting reference for container-runtime settings

adds container-runtime settings reference

---

content/en/faqitems/updates-1-how-long-variants.markdown
content/en/os/1.15.x/version-information/variants/index.markdown

Closes # n/a
Adds two notes about the update policy 

adds information on the update policy

---

content/en/os/1.15.x/api/settings/updates/_index.markdown
data/settings/1.15.x/updates.toml

Closes #230
Adds settings reference for updates

adds `settings.updates.*` setting reference

---

content/en/os/1.15.x/api/settings/network/_index.markdown
data/settings/1.15.x/network.toml

Closes #231 
Adds setting reference for (`settings.network.*`)

Network settings ref

---

content/en/os/1.15.x/api/settings/metrics/_index.markdown
data/settings/1.15.x/metrics.toml

Closes #232 
- Adds settings reference for `settings.metrics.*`

adds settings reference for metrics

---

data/versions/current.toml

Closes #311 
- Bumps patch version from 1.15.0 to 1.15.1

bump version metadata for 1.15.1

---

content/en/os/1.15.x/concepts/shell-less-host/index.markdown

Closes #263
- Removes inaccurate read-only reference
- Adds footnote about the mount containing both immutable and mutable parts

removes read-only message and adds note about im/mutability

---

content/en/os/1.15.x/version-information/gpu-drivers/1.15.1/index.markdown
content/en/os/1.15.x/version-information/gpu-drivers/_index.markdown
data/nvidia/1.15.1/kmod-5.10-nvidia.toml
data/nvidia/1.15.1/kmod-5.15-nvidia.toml
data/nvidia/1.15.1/kmod-6.1-nvidia.toml
layouts/shortcodes/nvidia-versions.html
scripts/nvidia-driver-versions/README.md
scripts/nvidia-driver-versions/create_data_file_from_cargo.sh
scripts/nvidia-driver-versions/create_markdown.sh
scripts/nvidia-driver-versions/get_cargos.sh
scripts/nvidia-driver-versions/index.markdown

Closes #252
- Adds scripts that can harvest the `kmod-*-nvidia/Cargo.toml` files from the bottlerocket-os/bottlerocket repo.
- Adds scripts that generate pages per patch bottlerocket version
- Adds a short code that reads the `Cargo.toml` files generates a table
- Adds a script readme to explain all of this

NVIDIA driver per variant list

---

content/en/os/1.16.x/version-information/gpu-drivers/1.16.0/index.markdown
content/en/os/1.16.x/version-information/gpu-drivers/_index.markdown
data/nvidia/1.16.0/kmod-5.10-nvidia.toml
data/nvidia/1.16.0/kmod-5.15-nvidia.toml
data/nvidia/1.16.0/kmod-6.1-nvidia.toml

Closes # n/a
Adds GPU drivers to 1.16.0

Adds GPU drivers info to 1.16.0

---

METADOC-SHORTCODES.md

Closes #330
Adds a document that describes the usage and purpose of the template shortcodes.

Documents shortcodes for documentation site

---

content/en/os/1.16.x/api/reporting/_index.markdown
content/en/os/1.16.x/api/reporting/cis-k8s/index.markdown
content/en/os/1.16.x/api/reporting/cis/index.markdown
content/en/os/1.16.x/concepts/api-driven/index.markdown
content/en/os/1.16.x/concepts/bootstrap-containers/_index.markdown
content/en/os/1.16.x/concepts/chain-of-trust/index.markdown
content/en/os/1.16.x/concepts/components/index.markdown
content/en/os/1.16.x/concepts/host-containers/_index.markdown
content/en/os/1.16.x/concepts/restricted-filesystem/index.markdown
content/en/os/1.16.x/concepts/shell-less-host/index.markdown
content/en/os/1.16.x/concepts/updating-bottlerocket/index.markdown
content/en/os/1.16.x/concepts/variants/index.markdown
content/en/os/1.16.x/install/quickstart/aws/ecs/index.markdown
content/en/os/1.16.x/install/quickstart/aws/host-containers/index.markdown
content/en/os/1.16.x/install/quickstart/aws/k8s/index.markdown
content/en/os/1.16.x/login/regaining-access/index.markdown
content/en/os/1.16.x/update/guidelines/index.markdown
content/en/os/1.16.x/update/locking-to-a-specific-release/index.markdown
content/en/os/1.16.x/update/methods/in-place/index.markdown
content/en/os/1.16.x/update/methods/node-replacement/index.markdown
data/repos/website.toml
layouts/shortcodes/on-github.html

Closes #347
- Creates a shortcode called "on-github" that will add a small snippet to file and issue or edit the page on github (`layouts/shortcodes/on-github.html`)
- Adds some information about the source github repo in a data file (`data/repos/website.toml`)
- Adds the widget to many, many pages.

Adds a widget to editable pages.

---

content/en/os/1.16.x/version-information/gpu-drivers/1.16.1/index.markdown
data/nvidia/1.16.1/kmod-5.10-nvidia.toml
data/nvidia/1.16.1/kmod-5.15-nvidia.toml
data/nvidia/1.16.1/kmod-6.1-nvidia.toml

Closes # 364
Adds GPU driver version information for 1.16.1 release

adds GPU version information for 1.16.1

---

data/versions/current.toml

Closes #364
increments patch version in data file

increment patch version to 1.16.1

---

content/en/os/1.17.x/version-information/gpu-drivers/1.17.0/index.markdown
data/nvidia/1.17.0/kmod-5.10-nvidia.toml
data/nvidia/1.17.0/kmod-5.15-nvidia.toml
data/nvidia/1.17.0/kmod-6.1-nvidia.toml

Closes # n/a
Adds GPU info to 1.17.0 documentation

1.17.0 gpu info

---

content/en/os/1.16.x/concepts/variants/index.markdown

Closes #376
Adds documentation for `updateinfo.xml` and `applications.json`

adds documentation for inventory and advisories

---

content/en/os/1.17.x/concepts/variants/index.markdown

Closes #376 
This PR replicates the content from #377 from 1.16.x docs to 1.17.x docs. No new documentation. Going forward all future versions will inherit this content.

Housekeeping: replicates content from #377 into 1.17.x docs

---

content/en/os/1.18.x/version-information/gpu-drivers/1.18.0/index.markdown
content/en/os/1.18.x/version-information/gpu-drivers/_index.markdown
content/en/os/1.18.x/version-information/packages/_index.markdown
data/nvidia/1.18.0/kmod-5.10-nvidia.toml
data/nvidia/1.18.0/kmod-5.15-nvidia.toml
data/nvidia/1.18.0/kmod-6.1-nvidia.toml

Closes #394 
- Adds GPU information about 1.18.0 from manual script run
- Fixes missing menu on variant info page

Manual GPU + errantly deleted menu fix

---

data/settings/1.19.x/ecs.toml

Closes #410
Adds `settings.ecs.awsvpc-block-imds` and `settings.ecs.backend-host` to docs

adds ecs 1.19.0 settings

---

data/versions/current.toml

Closes #413 
Increments the metadata for the 1.19.1 patch version

increment patch version to 1.19.1

---

content/en/os/1.19.x/version-information/gpu-drivers/1.19.1/index.markdown
content/en/os/1.19.x/version-information/packages/1.19.1/index.markdown
data/nvidia/1.19.1/kmod-5.10-nvidia.toml
data/nvidia/1.19.1/kmod-5.15-nvidia.toml
data/nvidia/1.19.1/kmod-6.1-nvidia.toml
data/versions/current.toml

Closes #413 
- Increments metadata for 1.19.1
Note: with the exception of incrementing the patch version, this is all generated from bottlerocket sources.

Docs for 1.19.1

---

content/en/os/1.19.x/concepts/api-driven/index.markdown

equlivent -> equivalent
Closes #

api-driven: fix typo

---

content/en/os/1.19.x/install/quickstart/aws/ecs/index.markdown

Closes #426
Updates the ECS quickstart to point to an existent link.

Changes link in ECS quickstart to AmazonECS_FullAccess docs

---

content/en/_index.markdown

Closes # n/a
Found incorrect link in site review

fix linking on homepage

---

content/en/os/1.19.x/version-information/gpu-drivers/1.19.2/index.markdown
data/nvidia/1.19.2/kmod-5.10-nvidia.toml
data/nvidia/1.19.2/kmod-5.15-nvidia.toml
data/nvidia/1.19.2/kmod-6.1-nvidia.toml
data/versions/current.toml

Closes #437
Increments version metadata. 
This also includes GPU driver information from `main` that were merged into `main` instead `1.19.2` branch (no changes)

Increments patch, adds missed gpu drivers

---

data/settings/1.14.x/ecs.toml
data/settings/1.15.x/ecs.toml
data/settings/1.16.x/ecs.toml
data/settings/1.17.x/ecs.toml
data/settings/1.18.x/ecs.toml
data/settings/1.19.x/ecs.toml

None
Fix the doc of ECS_CONTAINER_STOP_TIMEOUT

fix(doc): ECS_CONTAINER_STOP_TIMEOUT

---

content/en/faqitems/2_2-kubernetes-why-is-my-allocatable-memory-lower-than-expected.markdown

Add an FAQ item detailing allocatable memory behaviour when working with higher maxPods settings. 

Add allocatable memory FAQ item

---

content/en/os/1.19.x/install/quickstart/aws/ecs/index.markdown

Closes # n/a
1) Adds video walk through for console
2) Refactors headings to enable two major sections (CLI/Console)
3) Adds heading paragraph which includes link to containers on aws.

adds video and lightly refactors ECS quickstart

---

assets/scss/_styles_project.scss
content/en/ecs-updater/0.2.x/_index.markdown
content/en/ecs-updater/0.2.x/concepts/index.markdown
content/en/ecs-updater/0.2.x/operate/index.markdown
content/en/ecs-updater/0.2.x/setup/index.markdown
content/en/ecs-updater/0.2.x/troubleshoot/index.markdown
content/en/ecs-updater/0.2.x/uninstall/index.markdown
content/en/ecs-updater/_index.markdown
data/project_long_names.toml
data/versioned.toml
data/versions/current.toml
layouts/partials/ecs-updater/aws-service.html
layouts/partials/ecs-updater/fargate-task.html
layouts/partials/ecs-updater/node.html
layouts/shortcodes/ecs-updater/drain-ssm.html
layouts/shortcodes/ecs-updater/eventbridge-api-task.html
layouts/shortcodes/ecs-updater/node-3-ready.html
layouts/shortcodes/ecs-updater/node-ready-for-tasks.html
layouts/shortcodes/ecs-updater/updateable.html

Closes #24 
Documentation for ECS Updater
Todo:

initial for ecs-updater docs

---

content/en/faqitems/1_3-access-how-do-i-use-kubetl-debug.markdown

**Issue number:** https://github.com/bottlerocket-os/bottlerocket/issues/4011
Closes https://github.com/bottlerocket-os/bottlerocket/issues/4011
**Description of changes:** Add item to FAQ about how to use `kubectl debug node`

Add FAQ item about using kubectl debug node

---

content/en/faqitems/2_3-kubernetes-how-to-run-without-outbound.markdown
content/en/faqitems/6_2-troubleshooting-lustre.markdown

Added links to Github discussions and issues for EKS with limited outbound rules, and FSx for Lustre troubleshooting.

Add two FAQ items.

---

content/en/os/1.19.x/version-information/gpu-drivers/1.19.3/index.markdown
content/en/os/1.19.x/version-information/gpu-drivers/1.19.4/index.markdown
content/en/os/1.19.x/version-information/gpu-drivers/1.19.5/index.markdown
content/en/os/1.19.x/version-information/packages/1.19.3/index.markdown
content/en/os/1.19.x/version-information/packages/1.19.4/index.markdown
content/en/os/1.19.x/version-information/packages/1.19.5/index.markdown
data/nvidia/1.19.3/kmod-5.10-nvidia.toml
data/nvidia/1.19.3/kmod-5.15-nvidia.toml
data/nvidia/1.19.3/kmod-6.1-nvidia.toml
data/nvidia/1.19.4/kmod-5.10-nvidia.toml
data/nvidia/1.19.4/kmod-5.15-nvidia.toml
data/nvidia/1.19.4/kmod-6.1-nvidia.toml
data/nvidia/1.19.5/kmod-5.10-nvidia.toml
data/nvidia/1.19.5/kmod-5.15-nvidia.toml
data/nvidia/1.19.5/kmod-6.1-nvidia.toml
data/versions/current.toml

Closes # n/a
- Increments metadata for 1.19.5
Note: with the exception of incrementing the patch version, this is all generated from bottlerocket sources.

Docs for 1.19.5

---

content/en/os/1.20.x/version-information/gpu-drivers/1.20.1/index.markdown
content/en/os/1.20.x/version-information/gpu-drivers/1.20.2/index.markdown
content/en/os/1.20.x/version-information/gpu-drivers/1.20.3/index.markdown
content/en/os/1.20.x/version-information/packages/1.20.1/index.markdown
content/en/os/1.20.x/version-information/packages/1.20.2/index.markdown
content/en/os/1.20.x/version-information/packages/1.20.3/index.markdown
data/nvidia/1.20.1/kmod-5.10-nvidia.toml
data/nvidia/1.20.1/kmod-5.15-nvidia.toml
data/nvidia/1.20.1/kmod-6.1-nvidia.toml
data/nvidia/1.20.2/kmod-5.10-nvidia.toml
data/nvidia/1.20.2/kmod-5.15-nvidia.toml
data/nvidia/1.20.2/kmod-6.1-nvidia.toml
data/nvidia/1.20.3/kmod-5.10-nvidia.toml
data/nvidia/1.20.3/kmod-5.15-nvidia.toml
data/nvidia/1.20.3/kmod-6.1-nvidia.toml
data/versions/current.toml
layouts/shortcodes/nvidia-versions.html

Closes # n/a
- Increments metadata for 1.20.3
- Fixes script to address the changes to kmod-{kernel-version}-nvidia.toml files
Note: with the exception of incrementing the patch version (versions/current.toml) and nvidia-versions hugo script(layouts/shortcodes/nvidia-versions.html), this is all generated from bottlerocket sources.

Docs for 1.20.3

---

data/settings/1.20.x/autoscaling.toml
data/settings/1.20.x/aws.toml
data/settings/1.20.x/boot.toml
data/settings/1.20.x/bootstrap-containers.toml
data/settings/1.20.x/cloudformation.toml
data/settings/1.20.x/container-registry.toml
data/settings/1.20.x/container-runtime.toml
data/settings/1.20.x/dns.toml
data/settings/1.20.x/ecs.toml
data/settings/1.20.x/host-containers.toml
data/settings/1.20.x/kernel.toml
data/settings/1.20.x/kubernetes.toml
data/settings/1.20.x/metrics.toml
data/settings/1.20.x/motd.toml
data/settings/1.20.x/network.toml
data/settings/1.20.x/ntp.toml
data/settings/1.20.x/oci-defaults.toml
data/settings/1.20.x/oci-hooks.toml
data/settings/1.20.x/pki.toml
data/settings/1.20.x/updates.toml

Closes #
- Pulls forward docs relevant to api settings index for 1.19.0 to 1.20.0

Fixes missing api settings index

---

content/en/os/1.20.x/version-information/gpu-drivers/1.20.4/index.markdown
content/en/os/1.20.x/version-information/gpu-drivers/1.20.5/index.markdown
content/en/os/1.20.x/version-information/packages/1.20.4/index.markdown
content/en/os/1.20.x/version-information/packages/1.20.5/index.markdown
data/nvidia/1.20.4/kmod-5.10-nvidia.toml
data/nvidia/1.20.4/kmod-5.15-nvidia.toml
data/nvidia/1.20.4/kmod-6.1-nvidia.toml
data/nvidia/1.20.5/kmod-5.10-nvidia.toml
data/nvidia/1.20.5/kmod-5.15-nvidia.toml
data/nvidia/1.20.5/kmod-6.1-nvidia.toml
data/versions/current.toml

Closes # n/a
- Increments metadata for 1.20.5
Note: with the exception of incrementing the patch version in `current.toml`, this is all generated from bottlerocket sources.

Docs for 1.20.4 and 1.20.5

---

content/en/os/1.21.x/version-information/gpu-drivers/1.21.1/index.markdown
content/en/os/1.21.x/version-information/packages/1.21.1/index.markdown
data/nvidia/1.21.1/kmod-5.10-nvidia.toml
data/nvidia/1.21.1/kmod-5.15-nvidia.toml
data/nvidia/1.21.1/kmod-6.1-nvidia.toml
data/versions/current.toml

Closes # n/a
- Increments metadata for 1.21.1
Note: with the exception of 
- incrementing the patch version in `current.toml`
- manual updation of 1st and 3rd line of `content/en/os/1.21.x/version-information/packages/1.21.1/index.markdown`
this is all generated from bottlerocket sources.

Docs for 1.21.1

---

scripts/website-boiler-plate-generator/README.md
scripts/website-boiler-plate-generator/copy_files_from_prev_version.sh

Closes #
- This new script safely copies contents from previous minor version to next. 

scripts: Create script to copy contents from previous minor version to current

---

.github/workflows/hugo.yaml

Closes #
* This PR updates Github actions versions to latest.
**Testing**
* The same code was used to deploy to `piyush-jena.github.io`

Update Github Actions versions

---

content/en/os/1.29.x/version-information/packages/1.29.0/kernel-kit-packages.markdown
content/en/os/1.30.x/version-information/packages/1.30.0/kernel-kit-packages.markdown
content/en/os/1.31.x/version-information/packages/1.31.0/kernel-kit-packages.markdown
content/en/os/1.32.x/version-information/packages/1.32.0/kernel-kit-packages.markdown
content/en/os/1.33.x/version-information/packages/1.33.0/kernel-kit-packages.markdown
content/en/os/1.34.x/version-information/packages/1.34.0/kernel-kit-packages.markdown
content/en/os/1.35.x/version-information/packages/1.35.0/kernel-kit-packages.markdown
content/en/os/1.36.x/version-information/packages/1.36.0/kernel-kit-packages.markdown
content/en/os/1.37.x/version-information/packages/1.37.0/kernel-kit-packages.markdown
content/en/os/1.38.x/version-information/packages/1.38.0/kernel-kit-packages.markdown
content/en/os/1.39.x/version-information/packages/1.39.0/kernel-kit-packages.markdown
content/en/os/1.39.x/version-information/packages/1.39.1/kernel-kit-packages.markdown

Bug fix for cause of deployment failure. I tested the script again, and the current version in `main` generated the code correctly. 

Add missing " to kernel-kit-packages

---

content/en/os/1.44.x/api/settings/container-runtime-plugins/_index.markdown
data/settings/1.44.x/container-runtime-plugins.toml
data/settings/1.44.x/container-runtime.toml

Add documentation for soci-snapshotter settings added in Bottlerocket v1.44.0

website: add SOCI snapshotter configuration for v1.44.x
